# Generated by Django 5.0.3 on 2024-04-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=100)),
                ('CourseHours', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/%Y/%m/%d')),
                ('FromDate', models.DateTimeField(blank=True, null=True)),
                ('ToDate', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('NumberOfLectures', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('VideoID', models.AutoField(primary_key=True, serialize=False)),
                ('LectureTitle', models.CharField(max_length=100)),
                ('VideoNo', models.IntegerField()),
                ('Description', models.TextField()),
                ('VideoFile', models.FileField(upload_to='videos/%y/%m/%d')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EnrollmentDate', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.course')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.customer')),
            ],
        ),
    ]
