# Generated by Django 5.0.3 on 2024-06-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='NumberOfLectures',
        ),
        migrations.AddField(
            model_name='course',
            name='NumberOfRatings',
            field=models.IntegerField(default=0),
        ),
    ]
