# Generated by Django 5.0.3 on 2024-06-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_numberoflectures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='NumberOfLec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
