# Generated by Django 5.0.3 on 2025-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_enrollment_customer_enrollment_enrolleduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='NumberOfUploadedLec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
