# Generated by Django 5.0.3 on 2025-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_numberofuploadedlec'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursevideos',
            constraint=models.UniqueConstraint(fields=('CourseID', 'VideoNo'), name='unique_lecture_per_course'),
        ),
    ]
