# Generated by Django 5.0.3 on 2025-08-10 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_numberofuploadedlec'),
        ('orders', '0034_alter_order_payment_method'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The associated course for the payment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='The ID of the Stripe checkout session.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the payment record was created.'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The associated order for the payment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='The status of the payment (e.g., pending, succeeded, failed).', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who initiated the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
