# Generated by Django 5.0.3 on 2025-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymenthistory_options_paymenthistory_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='The ID of the Stripe Payment Intent associated with the transaction.', max_length=255, null=True, unique=True),
        ),
    ]
