# Generated by Django 5.0.3 on 2025-09-09 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('payment', '0004_paymenthistory_address_id_paymenthistory_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='address_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='address',
            field=models.ForeignKey(blank=True, help_text='The address used for the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
