# Generated by Django 5.0.3 on 2025-09-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_paymenthistory_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='address',
            new_name='address_id',
        ),
    ]
