# Generated by Django 5.0.3 on 2025-09-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_address_paymenthistory_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='order',
        ),
    ]
