# Generated by Django 5.0.3 on 2025-09-09 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_couponusage'),
        ('payment', '0007_remove_paymenthistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The associated order for the payment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
