# Generated by Django 5.0.3 on 2024-06-27 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_remove_customer_balance_remove_delivery_balance_and_more'),
        ('products', '0008_remove_product_reviews_alter_proimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Withdraw_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50)),
                ('transfer_type', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Instapay', 'Instapay'), ('Phone Wallet', 'Phone Wallet')], default='Bank Transfer', max_length=50)),
                ('transfer_status', models.CharField(choices=[('Created', 'Created'), ('Done', 'Done'), ('Refused', 'Refused')], default='Created', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Cash Back', 'Cash Back'), ('Returned Product', 'Returned Product'), ('Purshased Products', 'Purchased Products'), ('Refund Failed', 'Refund Failed')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('from_state', models.CharField(blank=True, max_length=250)),
                ('to_state', models.CharField(blank=True, max_length=250)),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled')], default='created', max_length=50)),
                ('initial_status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled')], default='created', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stripe_id', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.delivery')),
                ('from_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_order_supplier_address', to='accounts.address')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('related_order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_related_orders', to='returnrequest.returnrequest')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_Supplier_orders', to='accounts.supplier')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='returnreque_user_id_0d99b9_idx')],
            },
        ),
    ]
