# Generated by Django 5.0.3 on 2024-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnrequest', '0002_returnrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='initial_status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='created', max_length=50),
        ),
    ]
