# Generated by Django 5.0.3 on 2024-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnrequest', '0006_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Cash Back', 'Cash Back'), ('Returned Cash Back', 'Returned Cash Back'), ('Returned Product', 'Returned Product'), ('Purshased Products', 'Purchased Products'), ('Refund Failed', 'Refund Failed'), ('Delivery Fee', 'Delivery Fee'), ('purchased Course', 'Purchased Course'), ('Supplier Transform', 'Supplier Transform')], max_length=50),
        ),
    ]
