# Generated by Django 5.0.3 on 2025-09-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('returnrequest', '0008_alter_transactions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='initial_status',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='related_order',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='balance_withdraw_request',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_order_from_address', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pickup_scheduled', 'Pickup Scheduled'), ('in_transit_to_warehouse', 'In Transit to Warehouse'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('in_transit_to_supplier', 'In Transit to Supplier'), ('delivered_successfully', 'Delivered Successfully'), ('failed_delivery', 'Failed Delivery'), ('cancelled', 'Cancelled'), ('accepted_by_supplier', 'Accepted by Supplier'), ('rejected_by_supplier', 'Rejected by Supplier')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_order_to_address', to='accounts.address'),
        ),
        migrations.DeleteModel(
            name='DeliveryReturnRequest',
        ),
    ]
