# Generated by Django 5.0.3 on 2025-09-15 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0044_shipment_return_request_shipmentitem_return_request_and_more'),
        ('products', '0012_posters'),
        ('returnrequest', '0009_remove_returnrequest_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='delivery_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='delivery_person',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='to_state',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Item was damaged'), ('wrong_item', 'Received wrong item'), ('wrong_size', 'Wrong size or fit'), ('not_as_described', 'Not as described'), ('changed_mind', 'Changed my mind'), ('other', 'Other')], default='damaged', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(default='ae29a227-ec98-4805-8cc8-58297f6d8ab6', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='product',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='supplier',
            field=models.ForeignKey(default=112, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='accounts.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('RETURN_CREDIT', 'Return Credit'), ('RETURN_DEBIT', 'Return Debit'), ('PURCHASE', 'Purchase')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceWithdrawRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=50)),
                ('transfer_type', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Instapay', 'Instapay'), ('Phone Wallet', 'Phone Wallet')], default='Bank Transfer', max_length=50)),
                ('transfer_status', models.CharField(choices=[('Created', 'Created'), ('Done', 'Done'), ('Refused', 'Refused')], default='Created', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='returnrequest.transaction')),
            ],
            options={
                'verbose_name': 'Balance Withdraw Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Balance_Withdraw_Request',
        ),
        migrations.DeleteModel(
            name='transactions',
        ),
    ]
