# Generated by Django 5.0.3 on 2025-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnrequest', '0010_remove_transactions_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('RETURN_CREDIT', 'Return Credit'), ('RETURN_DEBIT', 'Return Debit'), ('CASH_BACK', 'Cash Back'), ('RETURNED_CASH_BACK', 'Returned Cash Back'), ('RETURNED_PRODUCT', 'Returned Product'), ('PURCHASED_PRODUCTS', 'Purchased Products'), ('DELIVERY_FEE', 'Delivery Fee'), ('SUPPLIER_TRANSFORM', 'Supplier Transform'), ('REFUND_FAILED', 'Refund Failed'), ('PURCHASED_COURSE', 'Purchased Course')], max_length=50),
        ),
    ]
