# Generated by Django 5.0.3 on 2025-10-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnrequest', '0011_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancewithdrawrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancewithdrawrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='balancewithdrawrequest',
            name='transfer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('WITHDRAWAL_CANCELLED', 'Withdrawal Cancelled'), ('RETURN_CREDIT', 'Return Credit'), ('RETURN_DEBIT', 'Return Debit'), ('CASH_BACK', 'Cash Back'), ('RETURNED_CASH_BACK', 'Returned Cash Back'), ('RETURNED_PRODUCT', 'Returned Product'), ('PURCHASED_PRODUCTS', 'Purchased Products'), ('DELIVERY_FEE', 'Delivery Fee'), ('SUPPLIER_TRANSFORM', 'Supplier Transform'), ('REFUND_FAILED', 'Refund Failed'), ('PURCHASED_COURSE', 'Purchased Course')], max_length=50),
        ),
    ]
