# Generated by Django 5.0.3 on 2025-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnrequest', '0012_balancewithdrawrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancewithdrawrequest',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='balancewithdrawrequest',
            name='transfer_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Awaiting Approval', 'Awaiting Approval'), ('Approved', 'Approved'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Failed', 'Failed')], default='Requested', max_length=50),
        ),
    ]
