# Generated by Django 5.0.3 on 2024-05-04 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='BuildingNO',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='State',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Street',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='BuildingNO',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='City',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='State',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='Street',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingNO', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
