# Generated by Django 5.0.3 on 2024-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_buildingno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='WithdrawMethod',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='WithdrawNO',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='DiscountVouchers',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='WithdrawMethod',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='WithdrawNO',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='currentOrders',
        ),
        migrations.AddField(
            model_name='user',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
