# Generated by Django 5.0.3 on 2024-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_balance_remove_delivery_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='accepted_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='accepted_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
