# Generated by Django 5.0.3 on 2024-07-06 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delivery_accepted_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
