# Generated by Django 5.0.3 on 2025-01-01 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_onetimepassword_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
