# Generated by Django 5.0.3 on 2025-01-18 00:37

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_onetimepassword_created_at'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Remove the Customer field
        migrations.RemoveField(
            model_name='follow',
            name='Customer',
        ),
    ]
