# Generated by Django 5.0.3 on 2025-07-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_onetimepassword_created_at'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_content_type', 'follower_object_id', 'supplier')},
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_content_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='FollowersNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierContract',
            field=models.FileField(upload_to='supplier_contracts/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierIdentity',
            field=models.FileField(upload_to='supplier_identities/%y/%m/%d'),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='Customer',
        ),
    ]
