# Generated by Django 5.0.3 on 2025-01-18 00:18

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType


def set_default_follower_content_type(apps, schema_editor):
    Follow = apps.get_model('accounts', 'Follow')
    Customer = apps.get_model('accounts', 'Customer')
    customer_content_type = ContentType.objects.get_for_model(Customer)

    for follow in Follow.objects.all():
        follow.follower_content_type = customer_content_type
        follow.follower_object_id = follow.customer.id  # Replace with actual mapping if needed
        follow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_onetimepassword_created_at'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='Customer',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_content_type',
            field=models.ForeignKey(
                default=1,  # Adjust this as needed
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_default_follower_content_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='follow',
            name='follower_content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_content_type', 'follower_object_id', 'supplier')},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='FollowersNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
