# Generated by Django 5.0.3 on 2025-01-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_content_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
