# Generated by Django 5.0.3 on 2024-06-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_supplier_user'),
        ('course', '0002_course_rating'),
        ('products', '0008_remove_product_reviews_alter_proimage_image'),
        ('reviews', '0002_review_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ease_of_place_order',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product_reviews_images/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_packaging',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='speed_of_delivery',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_rating', to='course.course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rating', to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rating', to='accounts.supplier'),
        ),
    ]
