# Generated by Django 5.0.3 on 2024-06-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_ease_of_place_order_review_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ease_of_place_order',
            field=models.IntegerField(blank=True, choices=[('Dissatisfied', 1), ('Satisfied', 2), ('Very Satisfied', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_packaging',
            field=models.IntegerField(blank=True, choices=[('Dissatisfied', 1), ('Satisfied', 2), ('Very Satisfied', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='speed_of_delivery',
            field=models.IntegerField(blank=True, choices=[('Dissatisfied', 1), ('Satisfied', 2), ('Very Satisfied', 3)], null=True),
        ),
    ]
