# Generated by Django 5.0.3 on 2024-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
