# Generated by Django 5.0.3 on 2024-05-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
