# Generated by Django 5.0.3 on 2024-05-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='ProductID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='product',
            new_name='Product',
        ),
    ]
