# Generated by Django 5.0.3 on 2024-05-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_productid_cartitems_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='User',
            new_name='user',
        ),
    ]
