# Generated by Django 5.0.3 on 2024-05-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_user_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='Product',
            new_name='product',
        ),
    ]
