# Generated by Django 5.0.3 on 2024-05-18 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_buildingno_remove_customer_city_and_more'),
        ('orders', '0008_rename_product_wishlistitem_product'),
        ('products', '0007_collection_collectionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('terms', models.TextField()),
                ('products', models.ManyToManyField(related_name='coupons', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.supplier')),
            ],
        ),
    ]
