# Generated by Django 5.0.3 on 2024-05-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='supplier',
            new_name='Supplier',
        ),
    ]
