# Generated by Django 5.0.3 on 2024-05-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_supplier_coupon_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
