# Generated by Django 5.0.3 on 2024-06-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delivery_governorate'),
        ('orders', '0016_order_confirmation_code_order_delivery_confirmed_at_and_more'),
        ('products', '0008_remove_product_reviews_alter_proimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='governorate',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
            ],
        ),
    ]
