# Generated by Django 5.0.3 on 2024-06-24 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delivery_governorate'),
        ('orders', '0018_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_supplier_address', to='accounts.address'),
        ),
    ]
