# Generated by Django 5.0.3 on 2024-06-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_supplier_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supplier_address',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='Address',
        ),
    ]
