# Generated by Django 5.0.3 on 2024-06-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_rename_supplier_address_order_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
