# Generated by Django 5.0.3 on 2024-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery')], default='created', max_length=50),
        ),
    ]
