# Generated by Django 5.0.3 on 2024-06-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_initial_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='related_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_orders', to='orders.order'),
        ),
    ]
