# Generated by Django 5.0.3 on 2024-06-26 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_buildingno'),
        ('orders', '0026_order_related_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_orders', to='accounts.supplier'),
        ),
    ]
