# Generated by Django 5.0.3 on 2024-06-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_payment_method_alter_order_stripe_id'),
        ('returnrequest', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='ReturnRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_return_orders', to='returnrequest.returnrequest'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='orders.order'),
        ),
    ]
