# Generated by Django 5.0.3 on 2025-08-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_remove_deliveryorder_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
