# Generated by Django 5.0.3 on 2025-08-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Size',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
