# Generated by Django 5.0.3 on 2025-08-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_remove_orderitem_color_remove_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
