# Generated by Django 5.0.3 on 2025-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash On Delivery'), ('Credit Card', 'Credit Card'), ('Balance', 'Balance')], default='Cash on Delivery', max_length=50),
        ),
    ]
