# Generated by Django 5.0.3 on 2025-08-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
    ]
