# Generated by Django 5.0.3 on 2025-09-02 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('orders', '0035_remove_order_product_remove_order_stripe_id'),
        ('products', '0011_collection_created_at_collectionitem_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(blank=True, max_length=250)),
                ('to_state', models.CharField(blank=True, max_length=250)),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled')], default='created', max_length=50)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_52f79a_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='initial_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='related_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.delivery'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_supplier_address', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.supplier'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_customer_address', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.shipment'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['shipment', 'product'], name='orders_orde_shipmen_a97478_idx'),
        ),
    ]
