# Generated by Django 5.0.3 on 2025-09-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_shipmentitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('ready_to_ship', 'Ready To Ship'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('ready_to_ship', 'Ready To Ship'), ('on my way', 'On My Way'), ('delivered to First warehouse', 'Delivered To First Warehouse'), ('In Transmit', 'In Transmit'), ('delivered to Second warehouse', 'Delivered To Second Warehouse'), ('delivered successfully', 'Delivered Successfully'), ('failed delivery', 'Failed Delivery'), ('cancelled', 'Cancelled')], default='created', max_length=50),
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
