# Generated by Django 5.0.3 on 2025-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
