# Generated by Django 5.0.3 on 2025-09-15 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('orders', '0043_alter_order_order_number'),
        ('returnrequest', '0009_remove_returnrequest_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='returnrequest.returnrequest'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='returnrequest.returnrequest'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='orders.orderitem'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', False), ('return_request__isnull', True)), models.Q(('order__isnull', True), ('return_request__isnull', False)), _connector='OR'), name='shipment_has_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order_item__isnull', False), ('return_request__isnull', True)), models.Q(('order_item__isnull', True), ('return_request__isnull', False)), _connector='OR'), name='shipment_item_has_one_parent'),
        ),
    ]
