# Generated by Django 5.0.3 on 2025-10-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_content_type_notification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
