# Generated by Django 5.0.3 on 2024-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='OutOfStock',
            field=models.BooleanField(),
        ),
    ]
