# Generated by Django 5.0.3 on 2024-05-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_outofstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(),
        ),
    ]
