# Generated by Django 5.0.3 on 2024-06-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_collection_collectionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Reviews',
        ),
        migrations.AlterField(
            model_name='proimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product_images/%y/%m/%d'),
        ),
    ]
