# Generated by Django 5.0.3 on 2024-07-03 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_reviews_alter_proimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DiscountPercentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
