# Generated by Django 5.0.3 on 2025-01-18 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_height_product_watt_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
