# Generated by Django 5.0.3 on 2025-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_collection_created_at_collectionitem_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_link', models.ImageField(upload_to='posters_images/%y/%m/%d')),
                ('redierct_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
