# Generated by Django 5.0.3 on 2025-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('products', '0012_posters'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ProductName', 'ProductDescription'], name='products_pr_Product_971b37_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['UnitPrice'], name='products_pr_UnitPri_618b96_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['Rating'], name='products_pr_Rating_5236fa_idx'),
        ),
    ]
